DROP TABLE pr_faktura_naglowek CASCADE CONSTRAINTS;

DROP TABLE pr_faktura_pozycja CASCADE CONSTRAINTS;

DROP TABLE pr_klient CASCADE CONSTRAINTS;

DROP TABLE pr_lek CASCADE CONSTRAINTS;

DROP TABLE pr_typ_leku CASCADE CONSTRAINTS;

DROP TABLE pr_wojewodztwa CASCADE CONSTRAINTS;

DROP TRIGGER TR_PR_INSERT_KLIENT;

DROP TRIGGER TR_PR_INSERT_LEK;

DROP TRIGGER TR_PR_NAGLOWEK;

DROP TRIGGER TR_PR_POZYCJA;

DROP SEQUENCE SEQ_PR_KLIENT;

DROP SEQUENCE SEQ_PR_LEK;

DROP SEQUENCE SEQ_PR_NAGLOWEK;

DROP FUNCTION FN_PR_DAJ_ILOSC_LEKU;

DROP FUNCTION FN_PR_DAJ_KOD_LEKU;

DROP FUNCTION FN_PR_DAJ_NR_KLIENTA;

DROP VIEW PR_KLIENCI_WYDATKI;

DROP VIEW PR_NAJLEPSZY_LEK;

DROP VIEW PR_OBROT_MIESIACE;

DROP PROCEDURE pr_pr_generuj;
